# Generated by Django 4.2.11 on 2024-03-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(max_length=20)),
                ('name', models.CharField(max_length=70)),
                ('quantity', models.IntegerField(max_length=20)),
                ('price', models.IntegerField(max_length=20)),
            ],
        ),
    ]
